<div class="row">

  <div class="col-md-6 col-xs-4 clearfix">
      <h1>Bootstrap 3 Test</h1>

  </div>

  <div class="col-md-6 col-xs-4 clearfix">
    <span class="visible-xs">Visible </span>
    <span class="hidden-sm">Hidden</span>
  </div>

  <div class="col-md-12 clearfix">
    <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/cover.jpg') ?>" alt="Responsive images" />
  </div>

  <div class="col-md-12 clearfix">
  <table class="table-condensed">
    <tbody>
      <tr>
        <td>Col 1</td>
        <td>Col 2</td>
        <td>Col 3</td>
        <td>Col 4</td>

      </tr>
    </tbody>

  </table>
  </div>

</div>
