<div class="content-footer">
  <div class="footer-wrap container">
      <ul>
          <li class="first col-sm-2 ">
            <h3>COMPANY</h3>
            <p><a href="http://localhost/mage/1901/about-us.html/">About Us</a></p>
            <p><a href="http://localhost/mage/1901/our-customer-says.html/">Customer Reviews</a></p>
            <p><a href="http://localhost/mage/1901/catalogsearch/term/popular/">Search Keywords</a></p>
            <p><a rel="nofollow" href="http://localhost/mage/1901/partner-program.html/">Partner Program</a></p>
            <p><a rel="nofollow" href="http://localhost/mage/1901/our-partners.html/">Official Partners</a></p>
            <p><a rel="nofollow" href="http://localhost/mage/1901/promotion-programs.html">Promotional Programs</a></p>
            <p><a target="_blank" href="http://giaytot.com">Giay Nam</a></p>
          </li>
          <li class="shopus col-sm-2">
          <h3>SHOP WITH US</h3>
          <p><a rel="nofollow" href="http://localhost/mage/1901/magento-extensions.html/">Magento Extensions</a></p>
          <p><a href="http://localhost/mage/1901/magento-affiliate-plus-extension.html">Affiliate+ Extension</a></p>
          <p><a rel="nofollow" href="http://localhost/mage/1901/magento-services.html/">Magento Services</a></p>
          <p><a rel="nofollow" href="http://localhost/mage/1901/free-magento-extensions.html/">Free Stuff</a></p>
          </li>
          <li class="support col-sm-2">
            <h3>Support</h3>
          <p><a rel="nofollow" href="http://localhost/mage/1901/faq/">FAQ</a></p>
          <p><a href="http://localhost/mage/1901/magento-tutorial">Magento Tutorial</a></p>
          <p><a target="_blank" href="http://localhost/mage/1901/community-helpdesk/">Community Helpdesk</a></p>
          <p><a target="_blank" rel="nofollow" href="https://support.magestore.com/">Ticket System</a></p>
          <p><a rel="nofollow" href="mailto:support@magestore.com">Email Us</a></p>
          <p><a rel="nofollow" href="http://localhost/mage/1901/product-policy.html/">Product Policy</a></p>
          <p><a rel="nofollow" href="http://localhost/mage/1901/terms-conditions.html/">Terms &amp; Conditions</a></p>
          <p><a rel="nofollow" href="http://localhost/mage/1901/privacy-policy.html/">Privacy policy</a></p>
          <p><a rel="nofollow" href="http://localhost/mage/1901/license-agreement.html/">License Agreement</a></p>
          </li>


      <li class="quicklinks col-sm-2">
        <h3>Quick Links</h3>

          <p>
            <a href="http://localhost/mage/1901/magento-extensions/magento-checkout.html" title="Magestore.com - Magento Extensions - Magento Checkout">
            Magento Checkout            </a>
            <!--a class="num-extension"></a-->
          </p>

          <p>
            <a href="http://localhost/mage/1901/magento-extensions/magento-affiliate.html" title="Magestore.com - Magento Extensions - Magento Affiliate">
            Magento Affiliate           </a>
            <!--a class="num-extension"></a-->
          </p>


          <p>
            <a href="http://localhost/mage/1901/magento-extensions/magento-gift-card.html" title="Magestore.com - Magento Extensions - Magento Gift card">
            Magento Gift card           </a>
            <!--a class="num-extension"></a-->
          </p>


          <p>
            <a href="http://localhost/mage/1901/magento-extensions/magento-auction.html" title="Magestore.com - Magento Extensions - Magento Auction">
            Magento Auction   </a>
            <!--a class="num-extension"></a-->
          </p>


          <p>
            <a href="http://localhost/mage/1901/magento-extensions/magento-shipping.html" title="Magestore.com - Magento Extensions - Magento Shipping">
            Magento Shipping            </a>
            <!--a class="num-extension"></a-->
          </p>


          <p>
            <a href="http://localhost/mage/1901/magento-extensions/magento-gift-wrap.html" title="Magestore.com - Magento Extensions - Magento Gift wrap">
            Magento Gift wrap           </a>
            <!--a class="num-extension"></a-->
          </p>


          <p>
            <a href="http://localhost/mage/1901/magento-extensions/magento-menu.html" title="Magestore.com - Magento Extensions - Magento Menu">
            Magento Menu            </a>
            <!--a class="num-extension"></a-->
          </p>


          <p>
            <a href="http://localhost/mage/1901/magento-extensions/magento-facebook.html" title="Magestore.com - Magento Extensions - Magento Facebook">
            Magento Facebook            </a>
            <!--a class="num-extension"></a-->
          </p>


          <p>
            <a href="http://localhost/mage/1901/magento-extensions/magento-banner.html" title="Magestore.com - Magento Extensions - Magento Banner">
            Magento Banner            </a>
            <!--a class="num-extension"></a-->
          </p>


          <p>
            <a href="http://localhost/mage/1901/magento-extensions/magento-tier-price.html" title="Magestore.com - Magento Extensions - Magento Tier Price">
            Magento Tier Price            </a>
            <!--a class="num-extension"></a-->
          </p>
            </li>
      <li class="last col-sm-2">
      <h3>&nbsp;</h3>


          <p>
            <a href="http://localhost/mage/1901/magento-extensions/magento-reward-points.html" title="Magestore.com - Magento Extensions - Magento Reward Points">
            Magento Reward Points           </a>
            <!--a class="num-extension"></a-->
          </p>


          <p>
            <a href="http://localhost/mage/1901/magento-extensions/magento-groupon.html" title="Magestore.com - Magento Extensions - Magento Groupon">
            Magento Groupon           </a>
            <!--a class="num-extension"></a-->
          </p>


          <p>
            <a href="http://localhost/mage/1901/magento-extensions/magento-image.html" title="Magestore.com - Magento Extensions - Magento Image">
            Magento Image           </a>
            <!--a class="num-extension"></a-->
          </p>


          <p>
            <a href="http://localhost/mage/1901/magento-extensions/magento-search.html" title="Magestore.com - Magento Extensions - Magento Search">
            Magento Search            </a>
            <!--a class="num-extension"></a-->
          </p>


          <p>
            <a href="http://localhost/mage/1901/magento-extensions/magento-support.html" title="Magestore.com - Magento Extensions - Magento Support">
            Magento Support           </a>
            <!--a class="num-extension"></a-->
          </p>


          <p>
            <a href="http://localhost/mage/1901/magento-extensions/magento-seo.html" title="Magestore.com - Magento Extensions - Magento SEO">
            Magento SEO           </a>
            <!--a class="num-extension"></a-->
          </p>


          <p>
            <a href="http://localhost/mage/1901/magento-extensions/magento-catalog.html" title="Magestore.com - Magento Extensions - Magento Catalog">
            Magento Catalog           </a>
            <!--a class="num-extension"></a-->
          </p>


          <p>
            <a href="http://localhost/mage/1901/magento-extensions/magento-promotions.html" title="Magestore.com - Magento Extensions - Magento Promotions">
            Magento Promotions            </a>
            <!--a class="num-extension"></a-->
          </p>
                                <p>
            <a href="http://localhost/mage/1901/magento-enterprise-extension.html/" title="Magestore.com - Magento Enterprise Extensions">
              Enterprise Extensions           </a>
            <!--a class="num-extension">24</a-->
          </p>


      </li>
        </ul>
  </div>

  <div class="newsletter-box container col-sm-12" id="newsletter-box">
      <form id="newsletter-validate-detail" method="post" action="https://localhost/mage/1901/newsletter/subscriber/new/">
        <div class="block-content">
      <label for="newsletter">Never miss important updates and promotions <br><span>We won't spam you!</span></label>
            <div class="input-box">
               <input type="text" class="input-text required-entry validate-email" placeholder="Leave your email address here" title="Sign up for our newsletter" id="newsletter" name="email">
            </div>
            <div class="actions">
                <button class="button" title="Subscribe" onclick="ga('send', {'hitType': 'event', 'eventCategory': 'Newsletter', 'eventAction': 'Click', 'eventLabel': 'Place a seat'});" type="submit"><span>PLACE A SEAT</span></button>
            </div>
        </div>
    </form>
  </div>
  <script type="text/javascript">
  var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
  </script>

  <div class="asp container">
    <div class="accept col-sm-4">
    <h3>We Accept</h3>
    <img alt="" src="http://localhost/mage/1901/skin/frontend/default/magestore7.2/images/update/paypal.png" class="first"> <img alt="" src="http://localhost/mage/1901/skin/frontend/default/magestore7.2/images/update/visa.png"> <img alt="" src="http://localhost/mage/1901/skin/frontend/default/magestore7.2/images/update/master-card.png"> <img alt="" src="http://localhost/mage/1901/skin/frontend/default/magestore7.2/images/update/american-express.png"> <img alt="" src="http://localhost/mage/1901/skin/frontend/default/magestore7.2/images/update/skrill.png"> <img alt="" src="http://localhost/mage/1901/skin/frontend/default/magestore7.2/images/update/jcb.png" class="last"></div>

    <div class="safe col-sm-4">
    <h3>Safe &amp; Reliable</h3>
    <img alt="" src="http://localhost/mage/1901/skin/frontend/default/magestore7.2/images/comodo-ssl-under-checkout-button.png" class="first"> <img alt="" src="http://localhost/mage/1901/skin/frontend/default/magestore7.2/images/secure-checkout-page-under-checkout-button.png"></div>

    <div class="partner col-sm-4">
    <h3>INDUSTRY PARTNER</h3>
    <img alt="" src="http://localhost/mage/1901/skin/frontend/default/magestore7.2/images/update/magento.png"></div>
  </div>

</div>
